"on":
  push:
    branches:
      - "*"
  pull_request: null

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ludeeus/action-shellcheck@0.2.1
